services:
  streamlit:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: "streamlit-app"
    ports:
      - "8501:8501"  # Streamlit exclusive port
    volumes:
      - ./data:/app/data
      - ./app:/app/app  # For development hot-reloading
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
    depends_on:
      prefect:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  prefect:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
    container_name: "prefect-server"
    ports:
      - "4200:4200"  # Prefect UI port only
    volumes:
      - ./data:/app/data
      - ./src:/app/src  # For flow code synchronization
    environment:
      - PREFECT_SERVER_DB_PATH=/app/data/prefect.db
      - PREFECT_HOME=/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  app-network:
    name: lightning-network
    driver: bridge

volumes:
  data:
    driver: local